### ISSUE TITLE
Unable to run the script on Windows 10 

### ISSUE THREAD

**Issue by syarz** [Technowlogy-Pushpender/aapfinder#3]
Hi, I'm trying to run this script on Windows 10 x64 but it gives me an error which I'm unable to fix on my own. When I type python3 aapfinder.py it gives an error like this.

Traceback (most recent call last):
  File "aapfinder.py", line 3, in <module>
    import requests, threading, argparse, socket, time, os, banners
ModuleNotFoundError: No module named 'requests'

Python working fine and path variable set correctly

Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

I'm using python 2.x and python 3.x

**Comment by PushpenderIndia** [comment]
I have updated the documentation please check it now.

You have to install `requests` module using this command:
**python -m pip install requests**

**Comment by syarz** [comment]
Thanks, It's working now.
